import bcrypt from "bcryptjs";

export async function getSeedData() {
  const defaultPassword = await bcrypt.hash("password123", 10);

  const users = [
    {
      name: "Dr. Rajeshwar Sharma",
      email: "admin@coalcompliance.gov.in",
      password_hash: defaultPassword,
      role: "admin",
      organization: "Ministry of Coal / DGMS Headquarters",
      phone: "+91 98310 12345",
    },
    {
      name: "Ananya Sen",
      email: "compliance@coalcompliance.gov.in",
      password_hash: defaultPassword,
      role: "compliance_officer",
      organization: "Eastern Coalfields Central Audit Cell",
      phone: "+91 94340 56789",
    },
    {
      name: "Vikramaditya Verma",
      email: "inspector@coalcompliance.gov.in",
      password_hash: defaultPassword,
      role: "mine_inspector",
      organization: "DGMS Dhanbad Region - Field Circle",
      phone: "+91 91234 56780",
    },
    {
      name: "Suresh Chandra Patel",
      email: "manager@coalcompliance.gov.in",
      password_hash: defaultPassword,
      role: "mine_manager",
      organization: "South Eastern Coalfields (SECL) Korba",
      phone: "+91 98765 43210",
    },
    {
      name: "Dr. Maya Swaminathan",
      email: "auditor@coalcompliance.gov.in",
      password_hash: defaultPassword,
      role: "auditor",
      organization: "National Green Tribunal (NGT) Monitoring Panel",
      phone: "+91 97110 88990",
    },
  ];

  const mines = [
    {
      code: "MINE-JH-01",
      name: "Jharia Deep Seam Colliery (Pit #4)",
      type: "Underground",
      coalfield: "Jharia Coalfield (BCCL)",
      state: "Jharkhand",
      operator: "Bharat Coking Coal Limited (BCCL)",
      capacity_mtpa: 2.8,
      area_sq_km: 14.5,
      status: "High Risk",
      safety_rating: "C",
      coordinates: { lat: 23.7431, lng: 86.4172 },
      compliance_score: 78.5,
      manager_name: "A. K. Mukherjee",
      contact_phone: "+91 94311 02938",
    },
    {
      code: "MINE-CG-02",
      name: "Gevra Mega Opencast Project",
      type: "Opencast",
      coalfield: "Korba Coalfield (SECL)",
      state: "Chhattisgarh",
      operator: "South Eastern Coalfields Limited (SECL)",
      capacity_mtpa: 52.0,
      area_sq_km: 41.2,
      status: "Active",
      safety_rating: "A",
      coordinates: { lat: 22.3595, lng: 82.5936 },
      compliance_score: 94.2,
      manager_name: "Suresh Chandra Patel",
      contact_phone: "+91 98765 43210",
    },
    {
      code: "MINE-MP-03",
      name: "Jayant Opencast Block-B",
      type: "Opencast",
      coalfield: "Singrauli Coalfield (NCL)",
      state: "Madhya Pradesh",
      operator: "Northern Coalfields Limited (NCL)",
      capacity_mtpa: 20.0,
      area_sq_km: 25.8,
      status: "Active",
      safety_rating: "A",
      coordinates: { lat: 24.1167, lng: 82.6167 },
      compliance_score: 91.0,
      manager_name: "R. P. Singh",
      contact_phone: "+91 94251 77332",
    },
    {
      code: "MINE-WB-04",
      name: "Raniganj Sripur Underground Incline",
      type: "Underground",
      coalfield: "Raniganj Coalfield (ECL)",
      state: "West Bengal",
      operator: "Eastern Coalfields Limited (ECL)",
      capacity_mtpa: 1.5,
      area_sq_km: 9.8,
      status: "Under Maintenance",
      safety_rating: "B",
      coordinates: { lat: 23.6167, lng: 87.0667 },
      compliance_score: 83.4,
      manager_name: "Debashis Banerjee",
      contact_phone: "+91 94341 99011",
    },
    {
      code: "MINE-OD-05",
      name: "Talcher Bhubaneswari Opencast Mine",
      type: "Opencast",
      coalfield: "Talcher Coalfield (MCL)",
      state: "Odisha",
      operator: "Mahanadi Coalfields Limited (MCL)",
      capacity_mtpa: 28.0,
      area_sq_km: 30.4,
      status: "Active",
      safety_rating: "A",
      coordinates: { lat: 20.95, lng: 85.2167 },
      compliance_score: 89.6,
      manager_name: "P. K. Pradhan",
      contact_phone: "+91 94370 88219",
    },
  ];

  const regulations = [
    {
      code: "DGMS-VENT-01",
      title: "Underground Mine Ventilation & Gas Detection",
      governing_body: "DGMS",
      category: "Mine Safety & Ventilation",
      description:
        "Every airway in an underground working shall maintain minimum air velocity and continuous methane detection. Methane (CH4) concentration in the return airway shall never exceed 0.75% and nowhere in workings shall exceed 1.25%.",
      threshold_limit: "CH4 <= 0.75% return, <= 1.25% face; CO <= 50 ppm",
      severity_level: "Critical",
      penalty_clause: "Immediate suspension of underground mining shift and statutory inquiry under Section 22 of Mines Act 1952.",
      inspection_frequency: "Daily",
    },
    {
      code: "MOEFCC-AIR-02",
      title: "Ambient Air Quality & Fugitive Dust Suppression",
      governing_body: "MoEFCC",
      category: "Air Quality",
      description:
        "Continuous ambient air quality monitoring (CAAQMS) for Particulate Matter (PM10 and PM2.5). Fixed mist sprayers on haul roads, coal handling plants (CHP), and crusher hoppers to maintain PM levels within national standards.",
      threshold_limit: "PM10 <= 100 µg/m³, PM2.5 <= 60 µg/m³ (24-hr avg)",
      severity_level: "High",
      penalty_clause: "Environmental Compensation levy under Polluter Pays principle and notice under Air Act 1981.",
      inspection_frequency: "Weekly",
    },
    {
      code: "CMR-STRATA-03",
      title: "Strata Control & Roof Support Plan (Underground)",
      governing_body: "CMR 2017",
      category: "Strata Control",
      description:
        "Scientific strata management plan approved by DGMS. Routine resin roof-bolting density check and tell-tale borehole extensometer readings within 48 hours of seam extraction.",
      threshold_limit: "Roof sag <= 5mm over 7 days; Bolting density 1.2m grid",
      severity_level: "Critical",
      penalty_clause: "Prohibition of extraction in unstable panels under CMR 2017 Regulation 123.",
      inspection_frequency: "Weekly",
    },
    {
      code: "CPCB-WATER-04",
      title: "Mine Discharge Water Effluent & Treatment (ETP/STP)",
      governing_body: "CPCB",
      category: "Water Management",
      description:
        "Effluent mine pit water pumped out must pass through settling tanks / oil-grease traps before release into local natural drainage. Regular testing of pH, Total Suspended Solids (TSS), and heavy metals.",
      threshold_limit: "pH 6.5 - 8.5; TSS <= 100 mg/L; Oil & Grease <= 10 mg/L",
      severity_level: "High",
      penalty_clause: "Closure notice under Section 33A of Water (Prevention and Control of Pollution) Act 1974.",
      inspection_frequency: "Monthly",
    },
    {
      code: "DGMS-OB-05",
      title: "Overburden (OB) Dump Stability & Slope Geometry",
      governing_body: "DGMS",
      category: "Overburden & Waste",
      description:
        "Individual bench height of overburden dump shall not exceed 30m, overall slope angle <= 28 degrees with geo-technical slope stability radar/sensor monitoring to prevent dump failures during monsoon.",
      threshold_limit: "Slope angle <= 28°; Factor of Safety >= 1.3",
      severity_level: "High",
      penalty_clause: "Mandatory regrading and halt of dumping operations within 200m buffer zone.",
      inspection_frequency: "Monthly",
    },
    {
      code: "CMR-OHS-06",
      title: "Mandatory Personal Protective Equipment (PPE) & Welfare",
      governing_body: "CMR 2017",
      category: "Worker Health & Welfare",
      description:
        "100% compliance on DGMS approved safety boots, ISI-certified helmets with cap lamps, self-rescuers for underground workers, dust masks, and audiometric/occupational health surveillance every 5 years.",
      threshold_limit: "100% PPE compliance for all pit workers",
      severity_level: "Medium",
      penalty_clause: "Denial of pit entry and supervisory fine under Mines Rules 1955.",
      inspection_frequency: "Daily",
    },
    {
      code: "DGMS-RETURN-07",
      title: "Statutory Annual & Monthly Safety Returns",
      governing_body: "Mines Act 1952",
      category: "Statutory Returns",
      description:
        "Timely submission of Form I, Form II, safety committee minutes, and explosive usage balance sheets to the Regional Inspector of Mines via the electronic portal.",
      threshold_limit: "Monthly return by 10th; Annual return by 20th January",
      severity_level: "Medium",
      penalty_clause: "Statutory late filing fine and compliance audit flag.",
      inspection_frequency: "Monthly",
    },
  ];

  return { users, mines, regulations };
}
